name: Node.js CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Clean build directory
        run: rm -rf /home/ubuntu/actions-runner/_work/social-listening-frontend/social-listening-frontend/build
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build  # Build the project
      - run: CI=false npm run build  # Temporarily disable treating warnings as errors
      - run: sudo systemctl restart nginx  # Restart Nginx if needed
